pipeline {
  agent {
    kubernetes {
      // Define the pod template with container template
      containerTemplate {
            name 'gradle'
            image 'gradle'
            command 'sleep'
            args '30d'
        }
    }
  }
  
  stages {
    stage('Checkout code and prepare environment') {
      steps {
        git url: 'https://github.com/dlambrig/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
        sh """
          cd Chapter08/sample1
          chmod +x gradlew
        """
      }
    }

    stage('Run pipeline against a gradle project - test branches') {
      when {
        not { branch 'main' }
      }
      steps {
         echo "I am the ${env.BRANCH_NAME} branch"
         sh """
           cd Chapter08/sample1; 
           ./gradlew test
		   ./gradlew jacocoTestReport
		   ./gradlew checkstyleMain
         """
      }
	  if (env.BRANCH_NAME == "main"){
		steps {
		 echo "I am the ${env.BRANCH_NAME} branch"
		 sh """
		   cd Chapter08/sample1; 
		   ./gradlew jacocoTestCoverageVerification
		 """
		}
      }
    }
  }
  post {
    always {
      echo 'pipeline completed'
    }
    success {
      echo 'tests pass!'
    }
    failure {
      echo 'tests fail!'
    }     
  }
}
