podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: centos
        image: centos
        command:
        - sleep
        args:
        - 99d
	  - name: gradle
        image: gradle:jdk8
        command:
        - sleep
        args:
        - 99d
      restartPolicy: Never
''') {
  node(POD_LABEL) {
    stage('First Stage') {
      git 'https://github.com/chhunkim3/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
      container('centos') {
        stage('start calculator') {
          sh '''
          cd Chapter09/sample1
          chmod +x ./kubectl
          ./kubectl apply -f calculator.yaml
          ./kubectl apply -f hazelcast.yaml
          '''
        }
      }
    }

  }
}
