podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: gradle
        image: gradle:jdk8
        command:
        - sleep
        args:
        - 99d
      restartPolicy: Never
''') {
  node(POD_LABEL) {
    stage('First Stage') {
      git 'https://github.com/chhunkim3/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
      container('gradle') {
        stage('start calculator') {
          sh '''
          cd Chapter09/sample1
          chmod +x gradlew
          ./gradlew acceptanceTest -Dcalculator.url=http://calculator-service:8080
          curl -i calculator-service:8080/sum?a=3\&b=3
          '''
        }
      }
    }

  }
}
