podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: gradle
        image: gradle:jdk8
        command:
        - sleep
        args:
        - 99d
      restartPolicy: Never
''') {
  node(POD_LABEL) {
    stage('First Stage') {
      git 'https://github.com/chhunkim3/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
      container('gradle') {
        stage('start calculator') {
          sh '''
            cd Chapter08/sample1
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            ./kubectl apply -f calculator.yaml
            ./kubectl apply -f hazelcast.yaml
            curl "calculator-service.devops-tools.svc.cluster.local:8080/sum?a=3\&b=4"
          '''
        }
      }
    }

  }
}
