pipeline {
   agent {
    kubernetes {
      // Define the pod template with container template
      containerTemplate {
            name 'gradle'
            image 'gradle'
            command 'sleep'
            args '30d'
        }
    }
  }
  
  stages {
    stage('Checkout code and prepare environment') {
      steps {
        git url: 'https://github.com/dlambrig/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
        sh """
          cd Chapter08/sample1
          chmod +x gradlew
        """
      }
    }

    stage('Run pipeline against a gradle project - Not Main Branch') {
      when {
	 not { branch 'main' }
      }
      steps {
         echo 'Unit test Not Main branch'
         sh """
           cd Chapter08/sample1; 
           ./gradlew test
	   ./gradlew testClasses
	   ./gradlew processTestResources
    	   ./gradlew compileTestJava
	   ./gradlew jacocoTestReport
         """
      } 
      post {
	success {
	  echo 'tests success!'
    	}
    	failure {
      	  echo 'tests fail!'
    	}
      }
    }

    stage('Build a container if this is NOT playground branch') {	  
      when {
	  not { branch 'playground' }
      }
      steps {
	container('kaniko') {
		echo 'Build Docker Image In Kubernetes Pod'
		sh '''
  		docker push chhunkim3/docker-registry:kaniko-ex8
    		kubectl apply -f pod.yaml
      		kubectl logs kaniko --follow
  		'''
	}
      }
    }
	  
    stage('Run pipeline against a gradle project - Main Branch') {	  
      when {
	  branch 'main'
      }
      steps {
	 echo 'Unit test Main Branch'
	 sh """
 	 cd Chapter08/sample1; 
	 ./gradlew jacocoTestCoverageVerification
	 """
      }
    }
  }

  post {
    always {
      echo 'pipeline completed'
    }
  }
}
