pipeline {
  agent {
    kubernetes {
      // Define the pod template with container template
      containerTemplate {
            name 'gradle'
            image 'gradle'
            command 'sleep'
            args '30d'
	}
    }
  }
  
  stages {
    stage('Checkout code and prepare environment') {
      steps {
        git url: 'https://github.com/dlambrig/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
        sh """
          cd Chapter08/sample1
          chmod +x gradlew
        """
      }
    }

    stage('Run pipeline against a gradle project - Non Main Branch') {
      when {
        not { branch 'main' && 'playground' }
      }
      steps {
         echo 'Unit test not main branch'
         sh """
           cd Chapter08/sample1; 
           ./gradlew test
	   ./gradlew testClasses
	   ./gradlew processTestResources
    	   ./gradlew compileTestJava
	   ./gradlew jacocoTestReport
         """
      } 
      post {
	success {
	  echo 'tests success!'
    	}
    	failure {
      	  echo 'tests fail!'
    	}
      }
    }

    stage('Run pipeline against a gradle project - Playground Branch') {	  
      when {
	  branch 'playground'
      }
      steps {
	 echo 'Unit test Playground Branch'
	 sh """
           cd Chapter08/sample1; 
           ./gradlew test
	   ./gradlew testClasses
	   ./gradlew processTestResources
    	   ./gradlew compileTestJava
	   ./gradlew jacocoTestReport
         """
      }
    }
	  
    stage('Run pipeline against a gradle project - Main Branch') {	  
      when {
	  branch 'main'
      }
      steps {
	 echo 'Unit test Main Branch'
	 sh """
 	 cd Chapter08/sample1; 
	 ./gradlew jacocoTestCoverageVerification
	 """
      }
    }
  }

  post {
    always {
      echo 'pipeline completed'
    }
  }
}
