pipeline {
   agent {
    kubernetes {
      // Define the pod template with container template
      containerTemplate {
            name 'gradle'
            image 'gradle'
            command 'sleep'
            args '30d'
        }
    }
  }
  
  stages {
    stage('Checkout code and prepare environment') {
      steps {
        git url: 'https://github.com/dlambrig/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'master'
        sh """
          cd Chapter08/sample1
          chmod +x gradlew
        """
      }
    }

    stage('Run pipeline against a gradle project - Not Main Branch') {
      when {
	 not { branch 'main' }
      }
      steps {
         echo 'Unit test Feature branch'
         sh """
           cd Chapter08/sample1; 
           ./gradlew test
	   ./gradlew testClasses
	   ./gradlew processTestResources
    	   ./gradlew compileTestJava
	   ./gradlew jacocoTestReport
         """
      } 
      post {
	success {
	  echo 'tests success!'
    	}
    	failure {
      	  echo 'tests fail!'
    	}
      }
    }

    stage('Build a container if this is NOT playground branch') {	  
      when {
	  not { branch 'playground' }
      }
      steps {
	container('kaniko') {
	    sh '''
	    echo 'FROM openjdk:8-jre' > Dockerfile
	    echo 'COPY ./calculator-0.0.1-SNAPSHOT.jar app.jar' >> Dockerfile
	    echo 'ENTRYPOINT ["java", "-jar", "app.jar"]' >> Dockerfile
	    mv /mnt/calculator-0.0.1-SNAPSHOT.jar .
	    /kaniko/executor --context `pwd` --destination dlambrig/hello-kaniko:1.0
	    '''
	 }
       }
    }
	  
    stage('Run pipeline against a gradle project - Main Branch') {	  
      when {
	  branch 'main'
      }
      steps {
	 echo 'Unit test Main Branch'
	 sh """
 	 cd Chapter08/sample1; 
	 ./gradlew jacocoTestCoverageVerification
	 """
      }
    }
  }

  post {
    always {
      echo 'pipeline completed'
    }
  }
}
